language: java
os: linux
dist: trusty
jdk: openjdk11
before_install:
  - chmod +x mvnw
install: true

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install

cache:
  directories:
    - '$HOME/.m2/repository'